import { Box, Flex, Image, Text } from "@chakra-ui/react"
import W1 from '../../assets/images/why1.png'
import W2 from "../../assets/images/why2.png";
import W3 from "../../assets/images/why3.png";
import W4 from "../../assets/images/why4.png";
import W5 from "../../assets/images/why5.png";
import W6 from "../../assets/images/why6.png";
import W7 from "../../assets/images/why7.png";
import W8 from "../../assets/images/why8.png";

const Card = () => {
  return (
    <>
      <Flex
        width={"100%"}
        height={"100%"}
        justifyContent={"center"}
        alignItems={"center"}
        gap={"20px"}
        direction={"column"}
      >
        <Flex gap={"20px"}>
          <Flex
            width={"360px"}
            height={"208px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"15px"}
          >
            <Flex>
              <Box
                width={"38.72949981689453px"}
                height={"38.302547454833984px"}
              >
                <Image
                  src={W1}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                AI-Driven OSCE Simulations
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                Fully voiced AI agents serve as standardized patients and exam
                assessors.
              </Text>
            </Flex>
          </Flex>
          <Flex
            width={"360px"}
            height={"208px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"10px"}
          >
            <Flex>
              <Box
                width={"38.72949981689453px"}
                height={"38.302547454833984px"}
              >
                <Image
                  src={W2}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                Comprehensive Question Banks
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                Extensive MCQs for Evaluating and Qualifying Exams
              </Text>
            </Flex>
          </Flex>
          <Flex
            width={"360px"}
            height={"208px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"10px"}
          >
            <Flex>
              <Box
                width={"38.72949981689453px"}
                height={"38.302547454833984px"}
              >
                <Image
                  src={W3}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                Unlimited Practice
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                No restrictions on when or how many times students can practice
              </Text>
            </Flex>
          </Flex>
        </Flex>
        <Flex gap={"20px"}>
          <Flex
            width={"550px"}
            height={"177px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"10px"}
          >
            <Flex>
              <Box
                width={"40px"}
                height={"40px"}
              >
                <Image
                  src={W4}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                Instant Feedback
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                AI assessors evaluate performance and provide actionable
                insights
              </Text>
            </Flex>
          </Flex>
          <Flex
            width={"550px"}
            height={"177px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"10px"}
          >
            <Flex>
              <Box
                width={"30px"}
                height={"35px"}
              >
                <Image
                  src={W5}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                Customizable Learning Experience
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                Tailored study plans to meet individual needs
              </Text>
            </Flex>
          </Flex>
        </Flex>
        <Flex gap={"20px"}>
          <Flex
            width={"360px"}
            height={"208px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"15px"}
          >
            <Flex>
              <Box
                width={"38.72949981689453px"}
                height={"38.302547454833984px"}
              >
                <Image
                  src={W6}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                AI-Driven OSCE Simulations
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                Fully voiced AI agents serve as standardized patients and exam
                assessors.
              </Text>
            </Flex>
          </Flex>
          <Flex
            width={"360px"}
            height={"208px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"10px"}
          >
            <Flex>
              <Box
                width={"38.72949981689453px"}
                height={"38.302547454833984px"}
              >
                <Image
                  src={W7}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                Comprehensive Question Banks
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                Extensive MCQs for Evaluating and Qualifying Exams
              </Text>
            </Flex>
          </Flex>
          <Flex
            width={"360px"}
            height={"208px"}
            bg={"#FFFFFF"}
            p={"20px"}
            borderRadius={"8px"}
            boxShadow={"lg"}
            direction={"column"}
            gap={"10px"}
          >
            <Flex>
              <Box
                width={"38.72949981689453px"}
                height={"38.302547454833984px"}
              >
                <Image
                  src={W8}
                  alt="img"
                  width={"100%"}
                  height={"100%"}
                  objectFit={"contain"}
                />
              </Box>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={700}
                fontSize={"20px"}
                color={"#191E33"}
              >
                Unlimited Practice
              </Text>
            </Flex>
            <Flex>
              <Text
                fontFamily={"Geist"}
                fontWeight={400}
                fontSize={"16px"}
                color={"#191E33"}
              >
                No restrictions on when or how many times students can practice
              </Text>
            </Flex>
          </Flex>
        </Flex>
      </Flex>
    </>
  );
}

export default Card
